Repository subconsciousnetwork/subconscious, pull requests merged in 2023-04, with the labels that each got.

#488 Refactor SphereProtocol to enable traverse on read
  xcode/Subconscious/Shared/Components/Common/Byline/SlashlinkBylineView.swift
  xcode/Subconscious/Shared/Components/Common/SlashlinkBarView.swift
  xcode/Subconscious/Shared/Components/Detail/MemoDetailDescription.swift
  xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
  xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
  xcode/Subconscious/Shared/Components/OmniboxView.swift
  xcode/Subconscious/Shared/Models/MemoAddress.swift
  xcode/Subconscious/Shared/Models/Petname.swift
  xcode/Subconscious/Shared/Models/Slashlink.swift
  xcode/Subconscious/Shared/Models/Slug.swift
  xcode/Subconscious/Shared/Services/AddressBookService.swift
  xcode/Subconscious/Shared/Services/DataService.swift
  xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
  xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
  xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift
  xcode/Subconscious/SubconsciousTests/Tests_Petname.swift
  xcode/Subconscious/SubconsciousTests/Tests_Slashlink.swift
  xcode/Subconscious/SubconsciousTests/Tests_Slug.swift
  xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift
Labels: Enhancement, Refactor

#494 Update to Noosphere v0.8.2
  xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Topic: Noosphere

#486 Implement basic 3p sphere content view
  xcode/Subconscious/Shared/Components/AppView.swift
  xcode/Subconscious/Shared/Components/Common/SubtextTextViewRepresentable.swift
  xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
  xcode/Subconscious/Shared/Components/Detail/MemoEditorDetailMetaSheetView.swift
  xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
  xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
  xcode/Subconscious/Shared/Components/FirstRun/RecoveryPhraseView.swift
  xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
  xcode/Subconscious/Shared/Config.swift
  xcode/Subconscious/Shared/Models/LoadingState.swift
  xcode/Subconscious/Shared/Parsers/SubtextAttributedStringRenderer.swift
  xcode/Subconscious/Shared/Services/PasteboardService.swift
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/SubconsciousTests/Tests_MemoViewerDetailMetaSheet.swift
  xcode/Subconscious/SubconsciousTests/Tests_RecoveryPhrase.swift
Labels: Topic: Multiplayer

#493 Read initial UserDefaultsProperty value from UserDefaults
  xcode/Subconscious/Shared/Library/UserDefaultsProperty.swift
  xcode/Subconscious/SubconsciousTests/Tests_UserDefaultProperty.swift
Labels: Bug

#496 Use ShareLink for sharing links
  xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailMetaSheetView.swift
  xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
  xcode/Subconscious/SubconsciousTests/Tests_MemoViewerDetailMetaSheet.swift
Labels: Enhancement

#501 Make all calls to Noosphere non-blocking on main thread
  xcode/Subconscious/Shared/Components/AddressBook/AddressBookModel.swift
  xcode/Subconscious/Shared/Components/AddressBook/AddressBookView.swift
  xcode/Subconscious/Shared/Components/AppView.swift
  xcode/Subconscious/Shared/Components/Common/Forms/Search.swift
  xcode/Subconscious/Shared/Components/Detail/MemoEditorDetail.swift
  xcode/Subconscious/Shared/Components/Detail/MemoViewerDetailView.swift
  xcode/Subconscious/Shared/Components/Detail/RenameSearchView.swift
  xcode/Subconscious/Shared/Components/Notebook/Notebook.swift
  xcode/Subconscious/Shared/Library/CombineUtilities.swift
  xcode/Subconscious/Shared/Library/Func.swift
  xcode/Subconscious/Shared/Services/AddressBookService.swift
  xcode/Subconscious/Shared/Services/DataService.swift
  xcode/Subconscious/Shared/Services/FeedService.swift
  xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
  xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
  xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/SubconsciousTests/TestUtilities.swift
  xcode/Subconscious/SubconsciousTests/Tests_CombineUtilities.swift
  xcode/Subconscious/SubconsciousTests/Tests_DataService.swift
  xcode/Subconscious/SubconsciousTests/Tests_Func.swift
  xcode/Subconscious/SubconsciousTests/Tests_NoosphereService.swift
  xcode/Subconscious/SubconsciousTests/Tests_Sphere.swift
Labels: Bug

#514 Implement callback-based Noosphere FFI
  xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
  xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
  xcode/Subconscious/Shared/Services/Noosphere/SphereFile.swift
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  xcode/Subconscious/SubconsciousTests/Tests_SphereFile.swift
Labels: Topic: Noosphere
