Repository subconsciousnetwork/subconscious, pull requests merged in 2023-05, with the labels that each got.

#576 Simplify `UserProfileService`
  xcode/Subconscious/Shared/Services/Noosphere/NoosphereService.swift
  xcode/Subconscious/Shared/Services/UserProfileService.swift
  xcode/Subconscious/SubconsciousTests/Tests_UserProfileService.swift
Labels: Bug

#595 Update Noosphere to e1021dc1
  xcode/Subconscious/Shared/Services/Noosphere/Noosphere.swift
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Topic: Noosphere

#594 Index 3P spheres in DB
  xcode/Subconscious/Shared/Components/AppView.swift
  xcode/Subconscious/Shared/Services/DataService.swift
  xcode/Subconscious/Shared/Services/DatabaseService.swift
  xcode/Subconscious/SubconsciousTests/Tests_DatabaseService.swift
Labels: Topic: Multiplayer, Topic: Noosphere

#624 Update Noosphere to d8488b68...
  xcode/Subconscious/Subconscious.xcodeproj/project.pbxproj
  xcode/Subconscious/Subconscious.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Topic: Multiplayer, Topic: Noosphere
